services:

  postgres:
    image: postgres:16.4
    container_name: cpsp4_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  n8n:
    image: n8nio/n8n:1.100.1
    container_name: cpsp4_n8n
    restart: unless-stopped

    ports:
      - "5679:5678"

    environment:
      - TZ=${TZ}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5679/

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./n8n_data:/home/node/.n8n


  appsmith:
    image: appsmith/appsmith-ce
    container_name: cpsp4_appsmith
    restart: unless-stopped

    ports:
      - "8081:80"

    depends_on:
      - postgres

    volumes:
      - ./appsmith_data:/appsmith-stacks

  pgadmin:
    image: dpage/pgadmin4
    container_name: cpsp4_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"

    depends_on:
      - postgres

    volumes:
      - ./pgadmin_data:/var/lib/pgadmin